### ISSUE TITLE
Id token has expired

### ISSUE THREAD

**Issue by cworf91** [servicecatalog/oscm-identity#77] opened 2019-11-15 12:06 UTC
**Version Info**
18.1 SSO

**Describe the bug**
When I try to register a new customer in SSO mode for a customer tenant. I get "ID token expired" after beeing logged in for a while.

**How to Reproduce**
1. Log in as supplier which is in the customer tenant
2. Click on "Register Costumer
3. Fill out the form with a customer, which is in the customer tenant

**Observed behavior**
Getting error. 

**Expected behavior**
Costumer should be created in OSCM 

**Screenshots**
![error](https://user-images.githubusercontent.com/44837963/68942315-9beb2300-07a8-11ea-840d-cbb1bb4abdd1.PNG)

![error2](https://user-images.githubusercontent.com/44837963/68942365-bde4a580-07a8-11ea-9f8f-b31a69942ef2.PNG)

**Comment by adamczykba** [comment] 2019-11-20 14:11
@cworf91 @GoebelL 
I gotta inform You that I wasn't able to reproduce this bug yet.
Both id-token refreshes just right for both admin and customer users.
@cworf91 Could You provide me with Jenkins and tenant config that You used to build the application?

**Comment by adamczykba** [comment] 2019-11-25 09:10
Closing this issue after discussion with @cworf91 as it's unable to reproduce at the moment.
We should reopen this bug if the issue is more evident in the future.

**Comment by cworf91** [comment] 2019-11-28 08:49
To provide more informations to this bug:
I was logged into OSCM and leave the office without shotdown my pc. OSCM use a keepAlive function that poll all the time. 
oscm\oscm-portal\WebContent\WEB-INF\facelets\tags\keepAlive.xhtml
this function is included in
\oscm-portal\WebContent\templates\header.xhtml

Probably the polling couses the token expired messages in the logfiles.

**Comment by adamczykba** [comment] 2019-11-29 16:49
@GoebelL @kowalczyka @cworf91 
I've managed to reproduce the problem.
The result is, the only case that actually results in an error visible for user is the one when user tries to refresh the page manually, while the token is expired. In normal usage (ex. user selects something from the menu), he is just re-logged and everything works fine.

How should we proceed with that? Maybe implement some auto-logout mechanism?

**Comment by GoebelL** [comment] 2019-12-02 09:58
@adamczykba, all 
Ok, I got it. Since the user impact is obviously less severe, I lower the priority.
Nevertheless it is bug and a fix candidate for the v18.1 release.

I consider following implementation to fix this issue.
**Idea**: Enhance the keep-a-live handling in oscm-portal with an oscm-identity notification. 

Steps:
1. Add a refresh function  in oscm-commons to refesh given IdToken from session. For example, reuse the code of existing refresh logic on invoking oscm-identity endpoints and extract this as separate function to be invoked from oscm-portal.
2. Implement a simple controller KeepAliveCtrl as managed bean in the oscm-portal.
3. Extend keepAlive.xhtml by adding an action listener on the a4j:poll function with an implementation in the KeepAliveCtrl. This bean extracts the IdToken from calling client session and delegates to the new refresh function in oscm-commons in order to renew this token.
 
This could be shared efforts. 

@adamczykba 
Please check if step 1 is doable at your side.

**Comment by GoebelL** [comment] 2019-12-03 13:22
As reported this issue is a special case, which applies with stale browser tab sessions. 
As discussed the proposed solution is not applicable on oscm-identity, as there is no solution for refreshing the user id token. Considering the low propability and minor user impact of this issue, the fix is not planed for now.

**Closed as completed by GoebelL** 2019-12-03 13:22 UTC
Labels: bug
